### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by moh1122** [iamyogish/SinchCalling_Swift#1]
Hey i have seen this proj in obj c thnk you for transforming it to swift but its not building with me i did a pod install and im running the .xcworkspace
but its giving two errors any clue ?

**Comment by iamyogish** [comment]
@moh1122 Could you please let me know which version of SinchRTC pod you're using. There is a problem in the SinchRTC 3.9.x and when I contacted the Sinch support, they said that it'll be fixed in next release. BTW could you brief about what is the error you're getting while you're building ? In the meanwhile I will try to build the project with latest pod in my free time and I will update you thanks.
P.S. While developed this example SinchRTC version was 3.7.1.

**Comment by moh1122** [comment]
hey thnks you for your reply well im using version 3.7.1 
the errors that are in my build are Sinch/Sinch.h file not found and failed to import bridging header 
any clue?

**Comment by moh1122** [comment]
hello any updates on the above

**Comment by iamyogish** [comment]
@moh1122 Hi Sorry for the delay in updating status. I was working on couple of other projects. The build error issue was because Sinch folks had made some changes to their SDK hence it was giving an error while we were building it. I had raised a ticket and they have fixed it in their newer version. You can run **pod update** to update the pods and the issue would be gone. Please let me know if you are able to resolve the issue so I can close this.

**Comment by moh1122** [comment]
Hello
thank you for the update. Its working fine now, but how can the user create a user name to call and how can they know the recipient name ?
i created a sinch account and added the keys to the appdelegate?
Can you please tell me more abt this?
Thank you

**Comment by iamyogish** [comment]
Hello, if you're integrating Sinch into your app what you need to do is you need to register user with a unique id or name in your app. For example in this demo app the name you first enter will be the name that I am registering you with Sinch, this can be an unique id or unique user name. The recepient name will be the other user id or user name (which again should be unique). Rest sinch will manage by looking up recepients for that particular app id. Hope this helps.

**Comment by moh1122** [comment]
thnks man
how can I use it to d0 app to phone not app to app

**Comment by iamyogish** [comment]
Hey I haven't tried that yet. You could be able to find something regarding this in Sinch documentation. Thanks.

**Comment by moh1122** [comment]
they dont have it in swift the only have objective c :(
